if has("gui_macvim")
  set guifont=Roboto\ Mono\ Light\ for\ Powerline:h12
  " set guifont=Monaco\ for\ Powerline:h14
  macmenu &Tools.Make key=<nop>
  vmap <D-b> <esc>:'<,'>:CoffeeCompile<CR>
  map <D-b> :CoffeeCompile<CR>
endif
