" Generic configuration
syntax on
set nocompatible
set number
set ruler
set encoding=utf-8 " Necessary to show Unicode glyphs
"set clipboard=unnamed,unnamedplus
"set shellcmdflag=-ic
set shell=/bin/zsh

" Start Vundle
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'gmarik/Vundle.vim'
Plugin 'scrooloose/nerdtree'
Plugin 'altercation/vim-colors-solarized'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'tpope/vim-fugitive'
Plugin 'airblade/vim-gitgutter'
Plugin 'mileszs/ack.vim'
Plugin 'edsono/vim-matchit'
Plugin 'scrooloose/nerdcommenter'
Plugin 'terryma/vim-multiple-cursors'
Plugin 'ervandew/supertab'

Plugin 'tomtom/tlib_vim'
Plugin 'MarcWeber/vim-addon-mw-utils'
Plugin 'garbas/vim-snipmate'
Plugin 'honza/vim-snippets'

Plugin 'skalnik/vim-vroom'
Plugin 'kchmck/vim-coffee-script'
Plugin 'tpope/vim-rails'
Plugin 't9md/vim-ruby-xmpfilter'
Plugin 'vim-ruby/vim-ruby'
Plugin 'nelstrom/vim-textobj-rubyblock'
Plugin 'kana/vim-textobj-user'
Plugin 'tpope/vim-projectionist'
Plugin 'tpope/vim-rake'
Plugin 'tpope/vim-bundler'
Plugin 'tpope/vim-surround'
Plugin 'kien/ctrlp.vim'
Plugin 'cakebaker/scss-syntax.vim'
Plugin 'mattn/emmet-vim'
Plugin 'slim-template/vim-slim'
Plugin 'scrooloose/syntastic'
Plugin 'othree/javascript-libraries-syntax.vim'
Plugin 'jelera/vim-javascript-syntax'
Plugin 'digitaltoad/vim-jade'
Plugin 'majutsushi/tagbar'
Plugin 'jeetsukumaran/vim-buffergator'
Plugin 'benmills/vimux'
Plugin 'mustache/vim-mustache-handlebars'

call vundle#end()

filetype indent plugin on
" End Vundle

autocmd! bufwritepost .vimrc source %
autocmd! bufwritepost ~/dotfiles/vim/vimrc source %

" remap the leader key
let mapleader=','

" Whitespace and tabs
set nowrap                        " don't wrap lines
set tabstop=2                     " a tab is two spaces
set shiftwidth=2                  " an autoindent (with <<) is two spaces
set expandtab                     " use spaces, not tabs
"set list                          " Show invisible characters
set backspace=indent,eol,start    " backspace through everything in insert mode
set textwidth=0
set wrapmargin=0

" Setup splitting where I want it
set splitbelow
set splitright

" Searching
"set hlsearch    " highlisht matches
set incsearch   " incremental searching
set ignorecase  " searches are case insensitive...
set smartcase   " ... unless they contain at least one capital letter
"nnoremap <silent> <F3> :nohlsearch<CR>

nnoremap <Leader>sw /<C-R>=expand('<cword>')<CR><CR>
nnoremap <Leader>sd /def <C-R>=expand('<cword>')<CR><CR>

" allow for %% to be the path of the current file
cabbr <expr> %% expand('%:p:h')

" Get the mouse working on terminal vim
" set ttyfast
" set mouse=a
" set ttymouse=xterm2

" Syntax formatting
nmap <silent> <C-c>= mtgg<S-v><S-g>='t<CR>

" Splits navigation
nmap <silent> <c-k> :wincmd k<CR>
nmap <silent> <c-j> :wincmd j<CR>
nmap <silent> <c-h> :wincmd h<CR>
nmap <silent> <c-l> :wincmd l<CR>

" SnipMate


" Configure ctags
map <F2> :echo system("git ctags")<CR>
map <silent> <F4> :tprev<CR>
map <silent> <F5> :tnext<CR>

" Configure tabbar
nmap <F8> :TagbarToggle<CR>

" Configure buffergator
nnoremap <silent> <C-c>p :BuffergatorMruCyclePrev<CR>
nnoremap <silent> <C-c>n :BuffergatorMruCycleNext<CR>

" Configure easytags
"set tags=./tags;
"let g:easytags_dynamic_files = 2
"let g:easytags_async = 1
"let g:easytags_auto_highlight = 0

" Configure tagbar
"nmap <F8> :TagbarToggle<CR>

" Configure NERDTree
nmap <leader>n :NERDTreeToggle<CR>
let NERDTreeIgnore=['\.pyc$', '\.pyo$', '\.rbc$', '\.rbo$', '\.class$', '\.o$', '\~$', 'tags', '\.idea', '\.swp$']
let NERDTreeShowHidden=1
let NERDTreeWinSize=45

set background=dark
"set background=light
if has('gui_running')
  let g:solarized_termtrans=0
else
  let g:solarized_termtrans=1
end
let g:solarized_bold=0
"let g:solarized_visibility="high"
let g:solarized_termcolors=256
"let g:solarized_contrast="normal"
colorscheme solarized

" to make gitgutter work with solarized
highlight clear SignColumn
call gitgutter#highlight#define_highlights()

" Configure vim-airline
let g:airline_theme="solarized"
let g:airline_powerline_fonts=1
set laststatus=2   " always show the status line
let g:airline#extensions#tmuxline#enabled = 0 " turn off the theme integration with tmuxline

" Configure vim-tmuxline
let g:tmuxline_theme='iceberg'

" Configure vim-fugitive
nmap <silent> <leader>gb :Gblame<CR>
nmap <silent> <leader>gs :Gstatus<CR>
nmap <silent> <leader>gd :Gdiff<CR>
nmap <silent> <leader>gl :Glog<CR>
nmap <silent> <leader>gc :Gcommit<CR>
nmap <silent> <leader>gp :Gpush<CR>

" Configure vim-syntastic
let g:syntastic_enable_signs=1
"let g:syntastic_quiet_messages={'level': 'warnings'}
let g:syntastic_auto_loc_list=2

" Configure vim-coffee-script
vmap <leader>bb <esc>:'<,'>:CoffeeCompile<CR>
map <leader>bb :CoffeeCompile<CR>

" Configure vim-ruby-xmpfilter
map <Leader>rs <Plug>(xmpfilter-mark)
map <Leader>rr <Plug>(xmpfilter-run)

" Configure vim-ctrlp (not currently in use)
let g:ctrlp_custom_ignore = {
            \ 'dir': '\.git$\|node_modules$\|\.hg$\|\.svn$',
            \ 'file': '\.exe$\|\.so$'
            \ }

let g:ctrlp_extensions = ['tag']

" Configure Vroom
let g:vroom_use_vimux=1
let g:vroom_use_bundle_exec=0
"let g:vroom_use_spring=1
let g:vroom_test_unit_command="testrbl -Itest" " make sure to run `gem install testrbl`
"let g:vroom_test_unit_command="m" " make sure to run `gem install m`

" Configure vimux
map <Leader>vp :VimuxPromptCommand<CR>
map <Leader>vl :VimuxRunLastCommand<CR>
map <Leader>vi :VimuxInspectRunner<CR>
map <Leader>vq :VimuxCloseRunner<CR>

" Configure Ack
nnoremap <leader>a :Ack! 
nnoremap <leader>u :Ack! <C-R>=expand('<cword>')<CR><CR>
let g:ack_default_options = " -s -H --nocolor --nogroup --column --ignore-dir=tmp --ignore-dir=coverage --ignore-dir=log --ignore-dir=node_modules --ignore-dir=\.idea --ignore-file=is:tags"

" Configure file types
autocmd BufNewFile,BufRead *.ejs set filetype=html
autocmd BufNewFile,BufReadPost *.jade set filetype=jade
autocmd BufNewFile,BufReadPost *.jade set filetype=jade

" Setup ignores (Taken from https://github.com/carlhuda/janus)
" Disable output and VCS files
set wildignore+=*.o,*.out,*.obj,.git,*.rbc,*.rbo,*.class,.svn,*.gem

" Disable archive files
set wildignore+=*.zip,*.tar.gz,*.tar.bz2,*.rar,*.tar.xz

" Ignore bundler and sass cache
set wildignore+=*/vendor/gems/*,*/vendor/cache/*,*/.bundle/*,*/.sass-cache/*

" Ignore librarian-chef, vagrant, test-kitchen and Berkshelf cache
set wildignore+=*/tmp/librarian/*,*/.vagrant/*,*/.kitchen/*,*/vendor/cookbooks/*

" Ignore rails temporary asset caches
set wildignore+=*/tmp/cache/assets/*/sprockets/*,*/tmp/cache/assets/*/sass/*

" Disable temp and backup files
set wildignore+=*.swp,*~,._*

" Backup and swap files
set backupdir^=~/.vim/_backup//    " where to put backup files.
set directory^=~/.vim/_temp//      " where to put swap files.
