" Load vim-pathogen
execute pathogen#infect()

" Generic configuration
syntax on
set nocompatible
set number
set ruler
set encoding=utf-8 " Necessary to show Unicode glyphs

if has("autocmd")
  filetype indent plugin on
endif

" Whitespace and tabs
set nowrap                        " don't wrap lines
set tabstop=2                     " a tab is two spaces
set shiftwidth=2                  " an autoindent (with <<) is two spaces
set expandtab                     " use spaces, not tabs
"set list                          " Show invisible characters
set backspace=indent,eol,start    " backspace through everything in insert mode

" Searching

set hlsearch    " highlight matches
set incsearch   " incremental searching
set ignorecase  " searches are case insensitive...
set smartcase   " ... unless they contain at least one capital letter

" Splits navigation
nmap <silent> <c-k> :wincmd k<CR>
nmap <silent> <c-j> :wincmd j<CR>
nmap <silent> <c-h> :wincmd h<CR>
nmap <silent> <c-l> :wincmd l<CR>

" Color Scheme
set background=dark
if has('gui_running')
  let g:solarized_termtrans=0
else
  let g:solarized_termtrans=1
end
let g:solarized_bold=0
let g:solarized_visibility="high"
let g:solarized_termcolors=256
let g:solarized_contrast="normal"
colorscheme solarized

" Configure vim-airline
let g:airline_theme="solarized"
let g:airline_powerline_fonts=1
set laststatus=2   " always show the status line

" Configure vim-fugitive
nmap <silent> <leader>gb :Gblame<CR>
nmap <silent> <leader>gs :Gstatus<CR>
nmap <silent> <leader>gd :Gdiff<CR>
nmap <silent> <leader>gl :Glog<CR>
nmap <silent> <leader>gc :Gcommit<CR>
nmap <silent> <leader>gp :Gpush<CR>

" Configure vim-syntastic
let g:syntastic_enable_signs=1
"let g:syntastic_quiet_messages={'level': 'warnings'}
let g:syntastic_auto_loc_list=2

" Configure vim-coffee-script
vmap <leader>bb <esc>:'<,'>:CoffeeCompile<CR>
map <leader>bb :CoffeeCompile<CR>
