# Don't print a new line at the start of the prompt
add_newline = false
command_timeout=1000

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[➜](bold red)"

[directory]
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = false

[aws]
disabled = true

[gcloud]
disabled = true

[hostname]
ssh_only = false

[username]
show_always = true

[docker_context]
disabled = true

# [ruby]
# disabled = true

# [nodejs]
# disabled = true
