# Don't print a new line at the start of the prompt
add_newline = false
command_timeout=1000

format = """
$username\
$hostname\
$shlvl\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$docker_context\
$deno\
$elixir\
$nodejs\
$python\
$ruby\
$terraform\
$memory_usage\
$aws\
$gcloud\
$cmd_duration\
$kubernetes\
$line_break\
$status\
${custom.insopshub}\
$shlvl\
$character"""

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[➜](bold red)"

[directory]
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = false

[aws]
disabled = true

[gcloud]
disabled = true

[kubernetes]
disabled = false

[kubernetes.context_aliases]
"(?P<env>.*)-inst-api-gateway-deployer" = "$env-instapig"

[hostname]
ssh_only = false

[username]
show_always = true

[docker_context]
disabled = true
format = "via [$symbol$context](blue bold) "

[status]
disabled = false

[shlvl]
disabled = false

[custom.insopshub]
command = "echo $VAULTED_ENV"
format = "$output "
when = "test -v VAULTED_ENV"

# [ruby]
# disabled = true

# [nodejs]
# disabled = true
