# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
#ZSH_THEME="kphoen"
#ZSH_THEME="pygmalion"
ZSH_THEME="mstarkman"
#ZSH_THEME="shades-of-purple"

UNBUNDLED_COMMANDS=(foreman spring)
plugins=(asdf git brew bundler docker docker-compose rbenv kubectl mutagen-compose)

export LIBRARY_PATH=$LIBRARY_PATH:/usr/local/opt/openssl/lib/
export PATH=/usr/local/bin:/usr/local/share/python:/usr/bin:/bin:/usr/sbin:/sbin:/usr/X11/bin:$PATH

source $ZSH/oh-my-zsh.sh

# Customize to your needs...

#export NODE_PATH=/usr/local/lib/node_modules

#export EDITOR='atom -n'
#export EDITOR='subl -n'
#export EDITOR='mvim'
#export EDITOR='vim'
export EDITOR='code -w'
export BUNDLER_EDITOR='code -n'

alias ls='ls -alh'
alias fdns='sudo dscacheutil -flushcache;sudo killall -HUP mDNSResponder; say cache flushed'

dev() {
  cd ~/Development/"$1"
}

_dev() { _files -W ~/Development -/; }

compdef _dev dev

### Added by the Heroku Toolbelt
#export PATH="/usr/local/heroku/bin:$PATH"

export GOPATH=$HOME/Development/go
export PATH=$PATH:$GOPATH/bin

# for tmuxinator
export DISABLE_AUTO_TITLE=true

ssh-add -K > /dev/null 2>&1

if [[ -e "$HOME"/.zshrc.local ]] then
  source $HOME/.zshrc.local
fi

#export NVM_DIR="$HOME/.nvm"
#[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

# Yarn
export PATH="$(yarn global bin):$PATH"

# Github signing of commits
export GPG_TTY=$(tty)

autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /usr/local/bin/terraform terraform

# configure starship
export STARSHIP_CONFIG=~/.config/starship.toml
eval "$(starship init zsh)"

export PATH=$PATH:/Applications/Postgres.app/Contents/Versions/latest/bin
export PATH=$PATH:$HOME/Development/bin

