# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
#ZSH_THEME="kphoen"
#ZSH_THEME="pygmalion"
ZSH_THEME="mstarkman"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"
#
# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Example format: plugins=(rails git textmate ruby lighthouse)
#
UNBUNDLED_COMMANDS=(foreman)
BUNDLED_COMMANDS=(lotus teaspoon)
plugins=(git brew bundler docker docker-compose)

export PATH=/usr/local/bin:/usr/local/share/python:/usr/bin:/bin:/usr/sbin:/sbin:/usr/X11/bin:$PATH
export PATH=$PATH:/Applications/Postgres.app/Contents/Versions/latest/bin
export PATH=$PATH:$HOME/Development/bin

export LIBRARY_PATH=$LIBRARY_PATH:/usr/local/opt/openssl/lib/

source $ZSH/oh-my-zsh.sh

# Customize to your needs...

#export NODE_PATH=/usr/local/lib/node_modules

#export EDITOR='atom -n'
#export EDITOR='subl -n'
#export EDITOR='mvim'
export EDITOR='vim'
#export EDITOR='code -n'

alias ls='ls -alh'
alias h='heroku'
alias fdns='sudo dscacheutil -flushcache;sudo killall -HUP mDNSResponder; say cache flushed'
alias gbDA='git branch | egrep -v "(master|\*)" | xargs git branch -D'
alias camerafix='sudo killall VDCAssistant'
#alias vim='mvim -v'
alias clear-rails-cache='rm -rf tmp/cache/[0-9,A-Z,a-z][0-9,A-Z,a-z][0-9,A-Z,a-z]'

dev() {
  cd ~/Development/"$1"
}

_dev() { _files -W ~/Development -/; }

compdef _dev dev

### Added by the Heroku Toolbelt
#export PATH="/usr/local/heroku/bin:$PATH"

export GOPATH=$HOME/Development/go
export PATH=$PATH:$GOPATH/bin

# for tmuxinator
export DISABLE_AUTO_TITLE=true

ssh-add -K > /dev/null 2>&1
ssh-add -K ~/.ssh/ec2_ssh_key > /dev/null 2>&1

if [[ -e "$HOME"/.zshrc.local ]] then
  source $HOME/.zshrc.local
fi

if [[ -e "$HOME"/.zshrc.alias.sanebox ]] then
  source $HOME/.zshrc.alias.sanebox
fi

#PATH=$HOME/.rvm/bin:$PATH # Add RVM to PATH for scripting
#export PATH="$HOME/.rbenv/bin:$PATH"
#if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi
#eval "$(rbenv init -)"
#set -o vi

#export PATH="$PATH:`#yarn global bin`"

#export NVM_DIR="$HOME/.nvm"
#[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

#[ -s "/Users/mark/.dnx/dnvm/dnvm.sh" ] && . "/Users/mark/.dnx/dnvm/dnvm.sh" # Load dnvm
#[[ -s "$HOME/.avn/bin/avn.sh" ]] && source "$HOME/.avn/bin/avn.sh" # load avn

#export PATH="$PATH:/Applications/Postgres.app/Contents/Versions/latest/bin"
#[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export PATH="/usr/local/opt/mysql@5.6/bin:$PATH"
export PATH="/usr/local/opt/sqlite/bin:$PATH"

# tabtab source for serverless package
# uninstall by removing these lines or running `tabtab uninstall serverless`
[[ -f /usr/local/lib/node_modules/serverless/node_modules/tabtab/.completions/serverless.zsh ]] && . /usr/local/lib/node_modules/serverless/node_modules/tabtab/.completions/serverless.zsh
# tabtab source for sls package
# uninstall by removing these lines or running `tabtab uninstall sls`
[[ -f /usr/local/lib/node_modules/serverless/node_modules/tabtab/.completions/sls.zsh ]] && . /usr/local/lib/node_modules/serverless/node_modules/tabtab/.completions/sls.zsh

. $HOME/.asdf/asdf.sh
. $HOME/.asdf/completions/asdf.bash

# set yarn binaries on path
# must be below the .asdf source commands ^
export PATH="$(yarn global bin):$PATH"
